name: Go Dependency Submission
on:
  workflow_dispatch:
  # release:
  #   types: [ published ]

# cancel in progress runs for the same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# The API requires write permission on the repository to submit dependencies
permissions:
  contents: write
  security-events: read

jobs:
  go-action-detection:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Extract Go version from go.mod
        id: go-version
        run: echo "version=$(grep '^go ' go.mod | awk '{print $2}')" >> "$GITHUB_OUTPUT"

      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version: ${{ steps.go-version.outputs.version }}

      - name: Fix cache permissions
        run: |
          chmod -R 0755 \
          ~/go/pkg/mod \
          ~/.cache/go-build \
          ~/.cache/golangci-lint \
          ~/.cache/buf/

      - name: Set up Go cache
        uses: actions/cache@caa296126883cff596d87d8935842f9db880ef25 # v5.1.0
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-amd64-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-amd64-go-

      - name: Get dependencies
        run: go mod download

      - name: run build
        run: go build -o bin/mcp-devtools

      - name: Run snapshot action
        uses: actions/go-dependency-submission@f35d5c9af13ce9cc32f7930b171e315e878f6921 # v2.0.3
        with:
          go-mod-path: go.mod
          go-build-target: bin/mcp-devtools
